import { ResponsiveFontScale } from './../services/ResponsiveFontScale';
export const ThemeFontSize = {
  1: ResponsiveFontScale(1),
  2: ResponsiveFontScale(2),
  3: ResponsiveFontScale(3),
  4: ResponsiveFontScale(4),
  5: ResponsiveFontScale(5),
  6: ResponsiveFontScale(6),
  7: ResponsiveFontScale(7),
  8: ResponsiveFontScale(8),
  9: ResponsiveFontScale(9),
  10: ResponsiveFontScale(10),
  12: ResponsiveFontScale(12),
  13: ResponsiveFontScale(13),
  14: ResponsiveFontScale(14),
  15: ResponsiveFontScale(15),
  16: ResponsiveFontScale(16),
  17: ResponsiveFontScale(17),
  18: ResponsiveFontScale(18),
  19: ResponsiveFontScale(19),
  20: ResponsiveFontScale(20),
  21: ResponsiveFontScale(21),
  22: ResponsiveFontScale(22),
  23: ResponsiveFontScale(23),
  24: ResponsiveFontScale(24),
  25: ResponsiveFontScale(25),
  26: ResponsiveFontScale(26),
  27: ResponsiveFontScale(27),
  28: ResponsiveFontScale(28),
  29: ResponsiveFontScale(29),
  30: ResponsiveFontScale(30),
};
